apiVersion: apps/v1
kind: Deployment
metadata:
  name: touchnote-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      touchnote_app: web
  template:
    metadata:
      labels:
        touchnote_app: web
    spec:
      containers:
      - name: app-site
        image: rahul2010/touchnote-review-analysis-app:latest
        ports:
        - containerPort: 5000